### PR TITLE
Update URL for cpt-city

### PR DESCRIPTION
**Pull request by sutaburosu**
The original URL for cpt-city now redirects to a mirror of the site, but it only redirects to the base URL rather than the full pathname. This behaviour breaks paletteknife.

The changes here point paletteknife directly to the mirror, which resolves the problem for me.

### CODE REVIEW

**Comment by kriegsman** [comment]
Thank you! Great catch, and great fix.  Very much appreciated, and thank you for helping with FastLED!

**Comment by sutaburosu** [comment]
You're welcome. Thanks for merging the fix so quickly.

I notice the original code is still present on fastled.io. I suspect some manual action must be taken to deploy the update there.

After this is done, I'll advise [the original reporter](https://www.reddit.com/r/FastLED/comments/11pa8y8/please_help_paletteknife_does_not_longer_work/lckhcko/) to use the official version of paletteknife, rather than the temporary fix on my own server.

**Comment by kriegsman** [comment]
Thank you - and thanks for the reminder that fastled.io site itself needs an update from the gh-pages repo.
@uberjay could you push the appropriate button for this?

**Comment by uberjay** [comment]
There were a few more buttons to press than expected, but the updates a live now! Thanks for the update!

**Comment by sutaburosu** [comment]
Thanks for your efforts, @uberjay, but I'm sorry to report that [the JS being served currently](http://fastled.io/tools/paletteknife/pk2.js) still contains the old URLs.

I've ruled out caching at my end by using `curl http://fastled.io/tools/paletteknife/pk2.js` from both my local machine and from a VPS in a different country which hasn't ever visited that URL previously.

**Comment by uberjay** [comment]
Turns out this repository is a decoy repository -- the content for fastled.io is (and has been for what looks like 11 years...) is in the gh-pages branch of https://github.com/FastLED/FastLED. I've merged this into the main repo and believe it's correct now. Please take a look and confirm it looks good to you!

@kriegsman also, probably we should just remove or make this repository private.

**Comment by sutaburosu** [comment]
Well done for figuring this out. Thanks, @uberjay.

**Pull request merged**
